Fix an UnboundLocalError where we accessed the `new` variable even if it was never assigned due to a failed if check
UnboundLocalError: cannot access local variable 'new' where it is not associated with a value